services:
  - type: web
    name: fraud-detection-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_REPO_ID
        value: KP022/fraud-detection-model
      - key: PYTHON_VERSION
        value: 3.11.0